name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          base: "header, repositories"
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Europe/Paris
          config_padding: 10%
      
          
      - name: Plugin Languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: "Yacc, css, vim, html, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, Makefile, Ruby, Vim Script, Python, ApacheConf" # List of comma separated languages to ignore
          plugin_languages_skipped: "" # List of comma separated repositories to skip
          base: ""
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          config_padding: 10%

      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 3
          
          
      - name: Gists
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_gists: yes

      - name: Latest tweets including attachments
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.tweets.attachments.svg
          token: NOT_NEEDED
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_attachments: yes
          plugin_tweets_user: alderoberge
          plugin_tweets_limit: 1
